aActionsIDs = [];

aActionsIDs = aActionsIDs + [player addAction["Take Fuel Can", "noscript.sqf", 'deleteVehicle (nearestobjects [player, ["Fuel_can"],  5] select 0); player setVariable["fuelFull",true,true]; hint "You have taken a fuel can."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [player, ["Fuel_can"],  5] select 0) < 4 and !(player getVariable "fuelFull") and ((nearestObjects[player, ["Fuel_can"], 3] select 0) getVariable "fuel")']];
aActionsIDs = aActionsIDs + [player addAction["Take Empty Fuel Can", "noscript.sqf", 'deleteVehicle (nearestobjects [player, ["Fuel_can"],  5] select 0); player setVariable["fuelEmpty",true,true]; hint "You have taken a empty fuel can."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [player, ["Fuel_can"],  5] select 0) < 4 and !(player getVariable "fuelEmpty") and !((nearestObjects[player, ["Fuel_can"], 3] select 0) getVariable ["fuel", false])']];
aActionsIDs = aActionsIDs + [player addAction["Take Repair kit", "noscript.sqf", 'deleteVehicle (nearestobjects [player, ["Suitcase"],  5] select 0); player setVariable["repairkits", (player getVariable "repairkits")+1,true]; hint "You have taken a repair kit."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [player, ["Suitcase"],  5] select 0) < 4 and (player getVariable "repairkits")<2']];
aActionsIDs = aActionsIDs + [player addAction["Take Medkit", "noscript.sqf", 'deleteVehicle (nearestobjects [player, ["CZ_VestPouch_EP1"],  5] select 0); player setVariable["medkits", (player getVariable "medkits")+1,true]; hint "You have taken a medkit."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [player, ["CZ_VestPouch_EP1"],  5] select 0) < 4 and (player getVariable "medkits")<2 ']];
aActionsIDs = aActionsIDs + [player addAction["Take Canned food", "noscript.sqf", '_nobj = (nearestobjects [player, ["Land_stand_small_EP1"],  5] select 0); _nobj setVariable["food",(_nobj getVariable "food")-1,true]; player setVariable["canfood",(player getVariable "canfood")+1,true]; player playmove "AinvPknlMstpSlayWrflDnon"; if(_nobj getVariable "food" < 1) then {_nobj spawn {_this setDamage 1.31337; sleep 2; deleteVehicle _this;}; hint "You have taken some canned food\nNo more food left on the table";} else {hint format["You have taken some canned food\n(Table still has %1)", (_nobj getVariable "food")];};',0,false,false,"",'player distance (nearestobjects [player, ["Land_stand_small_EP1"],  5] select 0) < 5 and (player getVariable "canfood") < 3 and (nearestobjects [player, ["Land_stand_small_EP1"],  5] select 0) getVariable "food" > 0']];
aActionsIDs = aActionsIDs + [player addAction["Take Canned food", "noscript.sqf", 'deleteVehicle (nearestobjects [player, ["Land_Bag_EP1"],  5] select 0); player setVariable["canfood", (player getVariable "canfood")+1,true]; hint "You have taken some canned food."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [player, ["Land_Bag_EP1"],  5] select 0) < 5 and (player getVariable "canfood")<3']];
aActionsIDs = aActionsIDs + [player addAction["Bottle up water", "noscript.sqf", '_nobj = (nearestobjects [player, ["Land_Barrel_water"],  5] select 0); _nobj setVariable["water",(_nobj getVariable "water")-1,true]; player setVariable["water",(player getVariable "water")+1,true]; player playmove "AinvPknlMstpSlayWrflDnon"; if(_nobj getVariable "water" < 1) then {_nobj spawn {_npos = getPos _this; _vecu = vectorUp _this; _vecd = vectorDir _this; deleteVehicle _this; _veh = createVehicle ["Land_Barrel_empty", _npos, [], 0, "CAN_COLLIDE"]; _veh setVectorDirAndUp [_vecd, _vecu]; _veh spawn {sleep 5; deleteVehicle _this};};hint "You have filled water bottle.\nBarrel is empty";} else {hint format["You have filled water bottle.\n(Water left: %1)", (_nobj getVariable "water")];};',0,false,false,"",'player distance (nearestobjects [player, ["Land_Barrel_water"],  5] select 0) < 5 and (player getVariable "water") < 4 and (nearestobjects [player, ["Land_Barrel_water"],  5] select 0) getVariable "water" > 0']];
aActionsIDs = aActionsIDs + [player addAction["Take bottle of water", "noscript.sqf", 'deleteVehicle (nearestobjects [player, ["Land_Teapot_EP1"],  5] select 0); player setVariable["water", (player getVariable "water")+1,true]; hint "You have taken a bottle of water."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [player, ["Land_Teapot_EP1"],  5] select 0) < 5 and (player getVariable "water")<4']];
aActionsIDs = aActionsIDs + [player addAction["Pickup Money", "core\misc\money.sqf", [], 1, false, false, "", 'player distance (nearestobjects [player, ["EvMoney"],  5] select 0) < 5']];
aActionsIDs = aActionsIDs + [player addAction["Fill Water Bottle", "noscript.sqf", ' player setVariable["water",(player getVariable "water")+1,true]; hint "You have filled a water bottle";',1,false,false,"",' player distance (nearestobjects [player, ["Land_pumpa"],  3] select 0) < 3 and (player getVariable "water")<4']];
aActionsIDs = aActionsIDs + [player addAction["Cook meat", "core\misc\cook.sqf", '', 1,false,false,"",'(player getVariable "rabitmeat" > 0 OR player getVariable "cowmeat" > 0 OR player getVariable "chickenmeat" > 0 OR player getVariable "goatmeat" > 0 OR player getVariable "boarmeat" > 0 OR player getVariable "sheepmeat" > 0) AND inflamed (nearestObjects[player, ["Land_Campfire_burning"],5] select 0);']];

//Refuel at gas stations
aActionsIDs = aActionsIDs + [player addAction["Refuel Fuel can", "noscript.sqf", 'player setVariable ["fuelFull",true,false]; player setVariable["fuelEmpty",false,false]; hint "Your fuel can is now full";',0,false,false,"",'player distance (nearestObjects[player, ["Land_A_FuelStation_Feed", "BarrelBase"], 3] select 0) < 3 AND !(player getVariable "fuelFull") AND (player getVariable "fuelEmpty")']];
/*
//Gut animal actions?
aActionsIDs = aActionsIDs + [player addAction["Take Raw Boar Meat", "noscript.sqf",'player switchMove "AinvPknlMstpSlayWrflDnon_medic"; WaitUntil {animationState player != "AinvPknlMstpSlayWrflDnon_medic"}; player setVariable["boarmeat", (player getVariable "boarmeat")+1,true]; deleteVehicle (nearestObjects[player, ["WildBoar"], 1] select 0); hint "You have taken some raw boar meat";',1,false,false,"",'not ALIVE (nearestObjects[player, ["WildBoar"],  1] select 0) AND player getVariable "boarmeat" < 3']];
aActionsIDs = aActionsIDs + [player addAction["Take Raw Chicken Meat", "noscript.sqf",'player switchMove "AinvPknlMstpSlayWrflDnon_medic"; WaitUntil {animationState player != "AinvPknlMstpSlayWrflDnon_medic"}; player setVariable["chickenmeat", (player getVariable "chickenmeat")+1,true]; deleteVehicle (nearestObjects[player, ["cock","hen"], 1] select 0); hint "You have taken some raw chicken meat";',1,false,false,"",'not ALIVE (nearestObjects[player, ["cock","hen"],  1] select 0) AND player getVariable "chickenmeat" < 3']];
aActionsIDs = aActionsIDs + [player addAction["Take Raw Cow Meat", "noscript.sqf",'player switchMove "AinvPknlMstpSlayWrflDnon_medic"; WaitUntil {animationState player != "AinvPknlMstpSlayWrflDnon_medic"}; player setVariable["cowmeat", (player getVariable "cowmeat")+1,true]; deleteVehicle (nearestObjects[player, ["Cow01","Cow02","Cow03","Cow04"], 1] select 0); hint "You have taken some raw cow meat";',1,false,false,"",'NOT ALIVE (nearestObjects[player, ["Cow01","Cow02","Cow03","Cow04"],  1] select 0) AND player getVariable "cowmeat" < 3']];
aActionsIDs = aActionsIDs + [player addAction["Take Raw Goat Meat", "noscript.sqf",'player switchMove "AinvPknlMstpSlayWrflDnon_medic"; WaitUntil {animationState player != "AinvPknlMstpSlayWrflDnon_medic"}; player setVariable["goatmeat", (player getVariable "goatmeat")+1,true]; deleteVehicle (nearestObjects[player, ["goat"], 1] select 0); hint "You have taken some raw goat meat";',1,false,false,"",'not ALIVE (nearestObjects[player, ["goat"],  1] select 0) AND player getVariable "goatmeat" < 3']];
aActionsIDs = aActionsIDs + [player addAction["Take Raw Rabbit Meat", "noscript.sqf",'player switchMove "AinvPknlMstpSlayWrflDnon_medic"; WaitUntil {animationState player != "AinvPknlMstpSlayWrflDnon_medic"}; player setVariable["rabitmeat", (player getVariable "rabitmeat")+1,true]; deleteVehicle (nearestObjects[player, ["Rabbit"], 1] select 0); hint "You have taken some raw rabbit meat";',1,false,false,"",'NOT ALIVE (nearestObjects[player, ["Rabbit"],  1] select 0) AND player getVariable "rabitmeat" < 3']];
aActionsIDs = aActionsIDs + [player addAction["Take Raw Sheep Meat", "noscript.sqf",'player switchMove "AinvPknlMstpSlayWrflDnon_medic"; WaitUntil {animationState player != "AinvPknlMstpSlayWrflDnon_medic"}; player setVariable["sheepmeat", (player getVariable "sheepmeat")+1,true]; deleteVehicle (nearestObjects[player, ["sheep"], 1] select 0); hint "You have taken some raw sheep meat";',1,false,false,"",'not ALIVE (nearestObjects[player, ["sheep"],  1] select 0) AND player getVariable "sheepmeat" < 3']];

//Raw Meat Pickup Actions
aActionsIDs = aActionsIDs + [player addAction["Take Raw Goat Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0); player setVariable["goatmeat", (player getVariable "goatmeat")+1,true]; hint "You have taken raw goat meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0) < 5 and (player getVariable "goatmeat")<3 and ((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "goat" AND ((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "raw")']];
aActionsIDs = aActionsIDs + [player addAction["Take Raw Cow Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0); player setVariable["cowmeat", (player getVariable "cowmeat")+1,true]; hint "You have taken raw cow meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0) < 5 and (player getVariable "cowmeat")<3 and ((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "cow" AND ((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "raw")']];
aActionsIDs = aActionsIDs + [player addAction["Take Raw Chicken Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0); player setVariable["chickenmeat", (player getVariable "chickenmeat")+1,true]; hint "You have taken raw chicken meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0) < 5 and (player getVariable "chickenmeat")<3 and ((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "chicken" AND ((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "raw")']];
aActionsIDs = aActionsIDs + [player addAction["Take Raw Boar Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0); player setVariable["boarmeat", (player getVariable "boarmeat")+1,true]; hint "You have taken raw boar meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0) < 5 and (player getVariable "boarmeat")<3 and ((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "boar" AND ((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "raw")']];
aActionsIDs = aActionsIDs + [player addAction["Take Raw Rabbit Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0); player setVariable["rabitmeat", (player getVariable "rabitmeat")+1,true]; hint "You have taken raw rabbit meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0) < 5 and (player getVariable "rabitmeat")<3 and ((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "rabit" AND ((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "raw")']];
aActionsIDs = aActionsIDs + [player addAction["Take Raw Sheep Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0); player setVariable["sheepmeat", (player getVariable "sheepmeat")+1,true]; hint "You have taken raw sheep meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0) < 5 and (player getVariable "sheepmeat")<3 and ((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "sheep" AND ((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "raw")']];

//Cooked Meat Pickup Actions
aActionsIDs = aActionsIDs + [player addAction["Take Cooked Goat Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0); player setVariable["goatmeatc", (player getVariable "goatmeatc")+1,true]; hint "You have taken Cooked goat meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0) < 5 and (player getVariable "goatmeat")<3 and ((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "goat" AND !((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "raw") AND player getVariable "goatmeatc" < 3']];
aActionsIDs = aActionsIDs + [player addAction["Take Cooked Cow Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0); player setVariable["cowmeatc", (player getVariable "cowmeatc")+1,true]; hint "You have taken Cooked cow meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0) < 5 and (player getVariable "cowmeat")<3 and ((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "cow" AND !((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "raw") AND player getVariable "cowmeatc" < 3']];
aActionsIDs = aActionsIDs + [player addAction["Take Cooked Chicken Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0); player setVariable["chickenmeatc", (player getVariable "chickenmeatc")+1,true]; hint "You have taken Cooked chicken meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0) < 5 and (player getVariable "chickenmeat")<3 and ((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "chicken" AND !((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "raw") AND player getVariable "chickenmeatc" < 3']];
aActionsIDs = aActionsIDs + [player addAction["Take Cooked Boar Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0); player setVariable["boarmeatc", (player getVariable "boarmeatc")+1,true]; hint "You have taken Cooked boar meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0) < 5 and (player getVariable "boarmeat")<3 and ((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "boar" AND !((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "raw") AND player getVariable "boarmeatc" < 3']];
aActionsIDs = aActionsIDs + [player addAction["Take Cooked Rabbit Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0); player setVariable["rabitmeatc", (player getVariable "rabitmeatc")+1,true]; hint "You have taken Cooked rabbit meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0) < 5 and (player getVariable "rabitmeat")<3 and ((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "rabit" AND !((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "raw") AND player getVariable "rabitmeatc" < 3']];
aActionsIDs = aActionsIDs + [player addAction["Take Cooked Sheep Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0); player setVariable["sheepmeatc", (player getVariable "sheepmeatc")+1,true]; hint "You have taken Cooked sheep meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [player, ["Land_Sack_EP1"],  5] select 0) < 5 and (player getVariable "sheepmeat")<3 and ((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "sheep" AND !((nearestObjects[player,["Land_Sack_EP1"], 5] select 0) getVariable "raw") AND player getVariable "sheepmeatc" < 3']];
*/

//Take bomb
aActionsIDs = aActionsIDs + [player addAction ["Take Bomb", "noscript.sqf", 
'player setVariable ["bombs",true,false];deleteVehicle (nearestobjects [player, ["bomb"],  2] select 0); hint "You have picked up a time bomb"; player playmove "AinvPknlMstpSlayWrflDnon"'
,0,false,false,"",
' player distance (nearestobjects [player, ["bomb"],  2] select 0) < 3 AND !((nearestobjects [player, ["bomb"],  2] select 0) getVariable "bArmed")'
]];