objectlist = ["M2StaticMG",
            "DSHKM_TK_INS_EP1",
            "DSHkM_Mini_TriPod",
            "KORD_high_UN_EP1",
            "M2HD_mini_TriPod",
            "EvMoney",
            "Base_WarfareBBarrier10xTall",
            "Base_WarfareBBarrier10x",
            "Land_Barrel_water",
            "Suitcase",
            "Land_HBarrier5",
            "Land_BagFenceLong",
            "Fort_EnvelopeBig_EP1",
            "Fort_EnvelopeSmall_EP1",
            "Land_Fort_Watchtower_EP1",
            "Land_HBarrier_large",
            "Land_HBarrier5",
            "Fort_Barricade",
            "Land_fort_rampart",
            "Land_fort_bagfence_round",
            "Land_fort_bagfence_long",
            "Land_stand_small_EP1",
            "Land_Misc_deerstand",
            "Land_BarGate2",
            "Land_ConcreteBlock",
            "Land_ConcreteRamp"];
            
militaryvehs = ["HMMWV",
                "HMMWV_M2",
                "HMMWV_Ambulance",
                "HMMWV_Ambulance_DES_EP1",
                "MTVR",
                "V3S_TK_EP1",
                "V3S_Open_TK_EP1",
                "Ural_CDF",
                "Ural_INS",
                "UralOpen_INS",
                "Ural_UN_EP1",
                "UAZ_CDF",
                "UAZ_RU",
                "UAZ_INS",
                "UAZ_Unarmed_UN_EP1",
                "UAZ_Unarmed_TK_EP1",
                "ArmoredSUV_PMC",
                "SUV_UN_EP1",
                "Offroad_DSHKM_Ins"];

carsArray = [];